name: Run CI
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  normal_ci:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run normal CI
        run: echo "Hello from other side"
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "hello"
        run: echo "goodbye"

