name: Testing the github action workflow

on: 
  push:[*]


jobs:
  
  Checks a new feature is deployed:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 

    - run: |
          git branch
  
  
  

