name: Testing the github action workflow

on: [push]
jobs:
  
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: |
          git branch
  
  destroy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "git dddddddddddddddddbranche"

  

