name: Run CI
on:
  push:
    branches:
      - '**'

jobs:
  normal_ci:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'feature-/*' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run normal CI
        run: echo "Hello from other side"

