name: Auto Deployment for Feature Branches

on:
  push:
    branches:
      - '**'

jobs:
  Change_the_configuration_of_the_deployment:
    runs-on: ubuntu-latest
    if: contains(github.ref_name,'feature-' )
   # if: ${{ github.ref_name == 'feature-' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run PR CI
        run: echo "hello world"
  
  Checking_a_Secert_Exist:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
    steps:
     - if: ${{env.MY_SECRET}}
       run: echo "I have the heyo secret"

  checking_if_github actions_can_pass_parameters:
    runs-on: ubuntu-latest
    env:
        MY_SS: ${{secrets.MY_SECRETS}}

  checking_if_github_seceret can be create:
    runs-on: ubuntu-latest
    - uses: gliech/create-github-secret-action@v1
      with:
        name: MY_SECRET
        value: Eternia
        pa_token: ${{ secrets.PA_TOKEN }}