name: Auto Deployment for Feature Branches

on:
  push:
    branches:
      - '**'

jobs:
  Change_the_configuration_of_the_deployment:
    runs-on: ubuntu-latest
    if: contains(github.ref_name,'feature-' )
   # if: ${{ github.ref_name == 'feature-' }}
    steps:
      uses: actions/checkout@v3
      
      name: Check_the_G.C.P._Metadata
        uses: 'google-github-actions/setup-gcloud@v0' 
        run: |
            gsutil ls -L -b gs://mytesthtml
                        

  