name: Auto Deployment for Feature Branches

on:
  push:
    branches:
      - '**'

jobs:
  Check_Branch_Metadata_and_Configure_Environment_Variable:
    runs-on: ubuntu-latest
    if: contains(github.ref_name,'feature-' )
   
    steps:
      - uses: actions/checkout@v3
      
        name: Check_the_G.C.P._Metadata
      - uses: 'google-github-actions/setup-gcloud@v0' 
      - run: echo "Hello World"
            
                        
